#!/bin/bash

## https://ftp.gnu.org/gnu/gcc/gcc-12.2.0/gcc-12.2.0.tar.gz
## https://ftp.gnu.org/gnu/binutils/binutils-2.39.tar.gz
BINUTILS_VERSION=2.44
GCC_VERSION=14.2.0
 

# Prompt the user user for the location of the cross compiler.
echo "Enter the location of the cross compiler (default: $HOME/opt/cross):"
read -r CROSS_COMPILER_LOCATION
if [ -z "$CROSS_COMPILER_LOCATION" ]; then
    CROSS_COMPILER_LOCATION="$HOME/opt/cross"
fi
echo "Cross compiler location: $CROSS_COMPILER_LOCATION"
mkdir -p $CROSS_COMPILER_LOCATION
cd $CROSS_COMPILER_LOCATION
echo "Creating cross compiler in $CROSS_COMPILER_LOCATION"
PREFIX=$CROSS_COMPILER_LOCATION


# Prompt the user for the target architecture.
echo "Enter the target architecture (default: x86_64-elf):"
read -r TARGET_ARCH
if [ -z "$TARGET_ARCH" ]; then
    TARGET_ARCH="x86_64-elf"
fi
echo "Target architecture: $TARGET_ARCH"
TARGET=$TARGET_ARCH
echo "Creating cross compiler for $TARGET"

cd /etc


## Test if local host is Arch based.
if [ -d /etc/pacman.d ]
then
    ## Run the Arch version of the install command.
    sudo pacman -S base-devel gmp libmpc mpfr -y
fi

## Test if local host is Debian based.
if [ -d /etc/apt ]
then
    ## Run the Debian version of the install command.
    sudo apt-get install build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo libisl-dev -y

fi
cd ~
wget https://ftp.gnu.org/gnu/binutils/binutils-$BINUTILS_VERSION.tar.gz
wget https://ftp.gnu.org/gnu/gcc/gcc-$GCC_VERSION/gcc-$GCC_VERSION.tar.gz

tar xfv binutils-$BINUTILS_VERSION.tar.gz
tar xfv gcc-$GCC_VERSION.tar.gz

mkdir -p build-binutils
mkdir -p build-gcc

cd build-binutils
../binutils-$BINUTILS_VERSION/configure --target=$TARGET --prefix="$PREFIX" --enable-interwork --enable-multilib --disable-nls --disable-werror
make
make install
cd ..

cd build-gcc
../gcc-$GCC_VERSION/configure --target=$TARGET --prefix="$PREFIX" --disable-nls --disable-libssp --enable-languages=c,c++ --without-headers 
make all-gcc
make all-target-libgcc
make install-gcc
make install-target-libgcc

cd ..
# DONT KNOW WHY sudo is required!
sudo rm -rd binutils-$BINUTILS_VERSION gcc-$GCC_VERSION binutils-$BINUTILS_VERSION.tar.gz gcc-$GCC_VERSION.tar.gz build-binutils build-gcc
echo 'export PATH="$PATH:$HOME/opt/cross/bin"' >> $HOME/.bashrc
source ~/.bashrc


