#!/bin/bash

## Platform Detection
detect_platform() {
    case "$(uname -s)" in
        MINGW*|MSYS*|CYGWIN*)
            echo "windows"
            ;;
        Linux|Darwin|*BSD|SunOS)
            echo "posix"
            ;;
        *)
            echo "unknown"
            ;;
    esac
}

PLATFORM=$(detect_platform)
echo "Detected platform: $PLATFORM"

# Check if running on Windows
if [ "$PLATFORM" = "windows" ]; then
    echo "Warning: This script is designed for POSIX systems. Windows detected."
    echo "Consider using WSL (Windows Subsystem for Linux) or a similar environment."
    read -p "Continue anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Exiting..."
        exit 1
    fi
elif [ "$PLATFORM" = "unknown" ]; then
    echo "Warning: Unknown platform detected. This script is designed for POSIX systems."
    read -p "Continue anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Exiting..."
        exit 1
    fi
fi

## https://ftp.gnu.org/gnu/gcc/gcc-12.2.0/gcc-12.2.0.tar.gz
## https://ftp.gnu.org/gnu/binutils/binutils-2.39.tar.gz
BINUTILS_VERSION=2.45
GCC_VERSION=15.2.0
GDB_VERSION=15.2

# Prompt the user user for the location of the cross compiler.
echo "Enter the location of the cross compiler (default: $HOME/opt/cross):"
read -r CROSS_COMPILER_LOCATION
if [ -z "$CROSS_COMPILER_LOCATION" ]; then
    CROSS_COMPILER_LOCATION="$HOME/opt/cross"
fi
echo "Cross compiler location: $CROSS_COMPILER_LOCATION"
mkdir -p "$CROSS_COMPILER_LOCATION"
cd "$CROSS_COMPILER_LOCATION" || exit 1
echo "Creating cross compiler in $CROSS_COMPILER_LOCATION"
PREFIX="$CROSS_COMPILER_LOCATION"


# Prompt the user for the target architecture.
echo "The script supports the following target architectures:"
echo "1) x86_64-elf (default)"
echo "2) i686-elf"
echo "Enter the target architecture (default: x86_64-elf):"
read -r TARGET_ARCH
if [ -z "$TARGET_ARCH" ]; then
    TARGET_ARCH="x86_64-elf"
elif [ "$TARGET_ARCH" = "i686-elf" ]; then
    TARGET_ARCH="i686-elf"

else
    echo "Unknown architecture specified. Using default: x86_64-elf"
    TARGET_ARCH="x86_64-elf"

fi
echo "Target architecture: $TARGET_ARCH"
TARGET=$TARGET_ARCH
echo "Creating cross compiler for $TARGET"

## Test if local host is Arch based.
if [ -d /etc/pacman.d ]
then
    ## Run the Arch version of the install command.
    sudo pacman -S base-devel gmp libmpc mpfr -y
fi

## Test if local host is Debian based.
if [ -d /etc/apt ]
then
    ## Run the Debian version of the install command.
    sudo apt-get install build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo libisl-dev -y
fi

wget "https://ftp.gnu.org/gnu/binutils/binutils-$BINUTILS_VERSION.tar.gz"
wget "https://ftp.gnu.org/gnu/gcc/gcc-$GCC_VERSION/gcc-$GCC_VERSION.tar.gz"
wget "https://ftp.gnu.org/gnu/gdb/gdb-$GDB_VERSION.tar.xz"
tar xfv binutils-$BINUTILS_VERSION.tar.gz
tar xfv gcc-$GCC_VERSION.tar.gz
tar xfv gdb-$GDB_VERSION.tar.xz

mkdir -p build-binutils
tar xfv "binutils-$BINUTILS_VERSION.tar.gz"
tar xfv "gcc-$GCC_VERSION.tar.gz"

mkdir -p build-binutils
mkdir -p build-gcc

cd build-binutils || exit 1
../binutils-$BINUTILS_VERSION/configure --target="$TARGET" --prefix="$PREFIX" --enable-interwork --enable-multilib --disable-nls --disable-werror
make
make install
cd ..

cd build-gcc || exit 1
../gcc-$GCC_VERSION/configure --target="$TARGET" --prefix="$PREFIX" --disable-nls --disable-libssp --enable-languages=c,c++ --without-headers 
make all-gcc
make all-target-libgcc
make install-gcc
make install-target-libgcc

cd ..

mkdir -p build-gdb
cd build-gdb || exit 1
../gdb-$GDB_VERSION/configure --target="$TARGET" --prefix="$PREFIX" --disable-nls --disable-werror
make
make install
cd ..
    
# DONT KNOW WHY sudo is required!
sudo rm -rf "binutils-$BINUTILS_VERSION" "gcc-$GCC_VERSION" "gdb-$GDB_VERSION" "gdb-$GDB_VERSION.tar.gz"  "binutils-$BINUTILS_VERSION.tar.gz" "gcc-$GCC_VERSION.tar.gz" "gdb-$GDB_VERSION.tar.xz" build-binutils build-gcc build-gdb
echo "export PREFIX=\"$CROSS_COMPILER_LOCATION\"" >> "$HOME/.bashrc"
echo "export PATH=\"\$PATH:$CROSS_COMPILER_LOCATION/bin\"" >> "$HOME/.bashrc"
echo "Everything is done! Please restart your terminal or run 'source ~/.bashrc' to update your PATH."
