#!/bin/bash

set -e

echo "This script sets up a Debian environment with essential development tools for operating system development for both BIOS and UEFI."

# Update package lists and upgrade existing packages
sudo apt-get update && sudo apt-get -y upgrade

 

# Install essential packages
ESSENTIAL_PACKAGES=(
    build-essential
    curl
    wget
    vim
    unzip
    mtools
    dosfstools
    nasm
    cmake 
    qemu-system-x86
    mingw-w64
    ovmf
)
sudo apt-get install -y "${ESSENTIAL_PACKAGES[@]}"
# Clean up
sudo apt-get clean
echo "Debian setup completed successfully."
echo "Now run the create-cross script to set up the cross compiler."


