#!/bin/bash

set -e

echo "INFO: This script sets up a fresh Debian environment with essential packages for development and cross-compilation."
echo "INFO: It adds the arm64 architecture and installs necessary tools."
echo "INFO: Ensure you have sudo privileges to run this script."
echo "INFO: This script assumes you already have GIT installed."

# Update package lists and upgrade existing packages
sudo apt-get update && sudo apt-get -y upgrade

if ! dpkg --print-foreign-architectures | grep -q arm64; then
    sudo dpkg --add-architecture arm64
fi

# Install essential packages
ESSENTIAL_PACKAGES=(
    build-essential
    curl
    wget
    vim
    unzip
    mtools
    dosfstools
    nasm
    gcc-aarch64-linux-gnu 
    g++-aarch64-linux-gnu
    cmake 
    qemu-system-arm 
    qemu-system-aarch64
    qemu-system-x86
)
sudo apt-get install -y "${ESSENTIAL_PACKAGES[@]}"
# Clean up
sudo apt-get clean
echo "Debian setup completed successfully."
echo "You now should add a cross compiler for aarch64 invoking the create-cross script."

